import Head from "next/head";
import Header from "../components/header";
import Meetinginfo from "../components/meetinginfo";
import Notes from "../components/notes";
import Chatinfo from "../components/chatinfo";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Meetinginfo />
      <div className={styles.subContainer}>
        <Notes images={data} />
        <Chatinfo images={data} />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch("https://reqres.in/api/users?page=1");
  const data = await res.json();
  return {
    props: { data },
  };
}
